sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        WxQ9/NXRQJxQo8muRHmzMQivEyki28CI7Q6gT1TL+JREehfZ0V6zSc/Wto/NYKCSzWL2BCwc+l5MZEgOvg0Ko/j2adgUjxIMt6TvhbKhcfl72+UvE0AWsHqASOY9VtOFfUnzd2186BIwWE/ZTXfKJTu3PBWZ79DZhamB1UoUSxkt/Potbb9Hl7Ay4ufIHWhED5C7VMVsQF0vjNpB0Hqyi9MU91H4YhDsmdfrjjrm1t2wYl16p8V/mgmAYgQnZAw2l6BVJx3fl7rbBoztblZMP5jSG0/cG8U8R73eu45Z/2gKnhkIf6ILU3SvD/8rmMjQd1hLXMKLwcLiLObZMq7gSKW0M7yfuuZ09sDVgCy5kxy0c1pEwo5FX2Au3tIcnX9yka8PEMd/cWuJP9fYHSNdSQQEe5J0Ejb6xBtqIsorvCuHJICBgbqvit943nX2uGr9Pq8pkjSp425L3Uhn3C8uqWaUu/erfMijI2sYh8mcOa6P53DqWglbw7JX/GdMZuWwd+npzq2vPXCH2ShbwKZFQnm+9RF8h/MJpEG5NlnrMc6kI8E0twI80oFmKTicrtPrCLK6EUKc3iILcM06201uHvcgv8w6rD/k2s5v25IvycgCXdhTib9k5bpouKUCEswlH2ULyWAMBwQyPdPHlKirvdEpVGDsvNnrqtQvnEQQ3ns=
    - secure: >-
        hXSz/u3hSblSTDC8EZrrWIDejCySmYAOyqmQI53VjJE0A/xJ20aQgzfhAnk0TFSjid7BeU2xUAonQfCHshEmxx7x1XalJOZN94KCpkkKm05DIUqU4ek7I46NWbFJbkTgEDGG0pLcV31XtvOCzlEq9AGwT51xO8k/M556pJvB+VKnM+Gg3YIncJqpD0jhqJiKc7OxH15SGpxwFiHoy6fpiJ0x8f3nXBuvnz5c2EZMIb6Npj+R8JUN5c70/cOpAIsTLFUcMWsZK/mDhldjNBAkfVfvcuyOj3Y0smbWtX3qv3lF/ae2f44RfcIFOCSkfeV21FIo6Uem2sJrzpFouGJRx6tRxqZZLXTPlETQuYF2yB9KF63w1OvwonIUt4cs8pT/ZG6PPSJ3NkTr8OGS9gMbfte6U8+qPAhbZMZ26zW6JIXPDCvAo3Gi1b7+zhrI7bccrE8Fy99YPlRWAdQ1CTEuLeEofjthcne3/Z1l/jmMxFO+u44Iz29UpIZK6DsvOHwb/cL/m65/OnfvALvLDmlonlFI197Mb2bUJLkCaBIwLo1dQgB7sL1snlOYAVGl5YNACxUDHkKLcLR52ADN9ZQ7p8bX1wiufiWbPatOogz9fR769ZkBogTWGqm1q0UUv+s/vIuaVtbZjIpoQKxPeYR4AKn0NFKOL1e/CWEOTunIccc=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
