sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        Axfcosn5gvB+JuZEPryo96YboXbnTk4S5pYdyPFVG5agxA4DpPwRULXqztRf0lKj3Vd9TAFidQRWUcujABEMN+Wh/uGKayt0GFxjCsrWq/iWGJ5e8Lc745PZr1eXOaelqAGN01dlfGFMLTd+BTW7fdouMtIdZdWAKAlObFwIBekFBgyRXf22nfA5Kx6KloeKa0eBoPLKtHh0JDoCTQJ6C9nk2e/wRXdRnby3/nnbFVd0bVzN0ciLdQBGPhSFLFnHkfM4gllVCFq5jn6OiQLfe4bnwvJDMtOzAcn2ygGSiMG9JokPtag6RUfv+miW/nHK2L1u0QQEW53TbAo880eyFTbR6t91gNAROICaQktr5S76Pd+V670NWuVu1DooRsjJVpwsuT+9s+jhB5clZL7GgNLEnC4u8qQlVbyfC39L+aFdOYpDJWezYXIJPCFf5QuR7JjLu51VHx9FRgCE7M+ybYJNf2IQwioKZ0VFhzlNHIu5pEqZjtzK/QXLbFmpE62c/sR4muxoxkSQYisXMcsas35nDPqfV3QU1PcLZ1Dh6qvwfZ6Ho2p2u9V49bqThjuA4K+U7QHavsjXAtTv/OLaN+fCiUAQDzqyTQtcMYcoa2Lgk/8L5CObRIeNLG8ZQWhX04qQnYDXp5jc18/EBoqkS/MNfsf3pjopax884Tdop5U=
    - secure: >-
        IFar6fmOHUfv4XjmWiaMdJwzQy7IEWHaJC2SBXJnOj6OqcpD8fTAf1K9P4w0RP0UaCPqQz/dTrQdV5AbtlwyTHF7pVrcCML0KSiSdacx/ATieAhBpqqp2hBRiOgFz1w3si8nyL1qO5CQKbUwxOkHzIP4lursa6jhS3pKDX/LY3WNcv6BlPg8UMsX5VZU2m90yfpSIC25NODDkgd0Gb0hR/HsJ/Br38EE2Ri/bGin8lP9yv4Zs7ecq0TBPepVpV5YQ0aE5pSyusUqwPtyNRuT5Qy9NYdo5I47ZFSXXyPCwNS+Fx8GVGJ/fXuC6FQg4HPT6gXaiW2VxSEmXVBxsiB9QzPyns/AOpaM7dvMk+yYJsHD5UwcjGtQdkxU9RCrNTnJcufzDonCfLaMUdBPTVwYJrXfO6junc0H2CA6BeO01jYmh/9hB54OVRJ9BvEGQYpzAGB9Vx/N25Wuz1z21Sr+Of5zQ8bitmxVSLeLCqaLFDH1WRqiTCEm0BvSiiwOMqgE2b4E9+BlvcoiCzWWnHvTH1Qd6j/GJXp6pMjtHFnbsfNTJbxq2RQF863enUOiVO8H6IFN4QmlMzvqAT7Fm6vEBuLd3j9IRkTp5rUr/e4TltyLOyIPzVD+DGIF2euG9cdK3NQw252KGrB1WNjqk0uob1NfxAejs5wibaSgu8lAqKA=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
